version: '3.8'

services:
  books-service:
    build:
      context: ./books-service
      dockerfile: dockerfile
    container_name: books-service
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: dockerfile
    container_name: transaction-service
    ports:
      - "3002:3002"
    env_file:
      - .env
    depends_on:
      - mongo

  account-service:
    build:
      context: ./account-service
      dockerfile: dockerfile
    container_name: account-service
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - mongo

  auth-service:
    build:
      context: ./auth-service
      dockerfile: dockerfile
    container_name: auth-service
    ports:
      - "3004:3004"
    env_file:
      - .env
    depends_on:
      - mongo

  fine-service:
    build:
      context: ./fine-service
      dockerfile: dockerfile
    container_name: fine-service
    ports:
      - "3009:3009"
    env_file:
      - .env
    depends_on:
      - mongo

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: dockerfile
    container_name: gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - books-service
      - transaction-service
      - account-service
      - auth-service
      - fine-service

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
